export const SKILL_LEVELS = {
  ENTRY: 'entry',
  INTERMEDIATE: 'intermediate',
  ADVANCED: 'advanced',
};

export const DOMAINS = {
  MECHANICAL: 'Mechanical Systems',
  ELECTRICAL: 'Electrical Systems',
  HYDRAULICS: 'Hydraulics & Pneumatics',
  PLC: 'PLCs & Controls',
  SAFETY: 'Safety & Procedures',
  TROUBLESHOOTING: 'Troubleshooting & Diagnostics',
};

export const QUESTION_TYPES = {
  MULTIPLE_CHOICE: 'multiple-choice',
  TRUE_FALSE: 'true-false',
};

export const USER_TYPES = {
  CANDIDATE: 'candidate',
  EMPLOYEE: 'employee',
};

export const ASSESSMENT_LEVELS = {
  LEVEL_1: {
    id: 'level1',
    name: 'Level 1 - Basic',
    description: 'Entry-level questions only',
    skillLevels: ['entry'],
    questionsPerDomain: 4,
  },
  LEVEL_2: {
    id: 'level2',
    name: 'Level 2 - Intermediate',
    description: 'Entry and intermediate questions',
    skillLevels: ['entry', 'intermediate'],
    questionsPerDomain: 5,
  },
  LEVEL_3: {
    id: 'level3',
    name: 'Level 3 - Advanced',
    description: 'Intermediate and advanced questions',
    skillLevels: ['intermediate', 'advanced'],
    questionsPerDomain: 5,
  },
  LEVEL_4: {
    id: 'level4',
    name: 'Level 4 - Comprehensive',
    description: 'All questions from all difficulty levels',
    skillLevels: ['entry', 'intermediate', 'advanced'],
    questionsPerDomain: null, // null means all questions
  },
};

export const QUESTION_BANK = {
  mechanical: {
    entry: [
      {
        id: 'mech_e_1',
        question: 'What is the primary purpose of a bearing in mechanical systems?',
        options: ['To increase friction between moving parts', 'To reduce friction and support rotating shafts', 'To prevent lubrication from entering the system', 'To increase the weight of the assembly'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_e_2',
        question: 'A V-belt that is too tight will cause premature bearing failure.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_e_3',
        question: 'Which tool is most appropriate for checking shaft alignment?',
        options: ['Dial indicator', 'Torque wrench', 'Multimeter', 'Feeler gauge only'],
        correct: 0,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_e_4',
        question: 'Proper lubrication intervals are unnecessary if equipment appears to be running smoothly.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_e_5',
        question: 'What type of coupling allows for minor misalignment between shafts?',
        options: ['Rigid coupling', 'Flexible coupling', 'Flange coupling', 'Sleeve coupling'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_e_6',
        question: 'Ball bearings are designed to handle primarily radial loads.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_e_7',
        question: 'What is the purpose of a keyway in a shaft?',
        options: ['To reduce weight', 'To prevent rotation between shaft and attached component', 'To allow for thermal expansion', 'To improve lubrication flow'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_e_8',
        question: 'A set screw is used to permanently attach a pulley to a shaft.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.MECHANICAL,
      }
    ],
    intermediate: [
      {
        id: 'mech_i_1',
        question: 'When aligning a motor to a pump using the rim-and-face method, what are you measuring?',
        options: ['Angular and parallel misalignment', 'Vibration amplitude only', 'Electrical resistance', 'Temperature differential'],
        correct: 0,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_i_2',
        question: 'The proper torque sequence for a flange with 8 bolts is to tighten them in a star pattern.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_i_3',
        question: 'What is the most likely cause of excessive vibration in a rotating assembly?',
        options: ['Proper lubrication', 'Dynamic imbalance or misalignment', 'Correct belt tension', 'New bearings'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_i_4',
        question: 'Shaft runout should be measured with the coupling installed to get an accurate reading.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_i_5',
        question: 'What does "soft foot" refer to in machine alignment?',
        options: ['A worn bearing', 'Uneven mounting surface causing machine frame distortion', 'Incorrect belt tension', 'Damaged coupling'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_i_6',
        question: 'Thermal growth must be considered when aligning equipment that operates at elevated temperatures.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_i_7',
        question: 'A gear reducer with an output speed of 100 RPM and input speed of 1750 RPM has what gear ratio?',
        options: ['17.5:1', '1:17.5', '100:1', '1750:1'],
        correct: 0,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_i_8',
        question: 'Over-greasing a bearing can cause it to overheat and fail.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_i_9',
        question: 'What is the purpose of a mechanical seal in a pump?',
        options: ['To increase flow rate', 'To prevent leakage along the rotating shaft', 'To regulate pressure', 'To filter contaminants'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ],
    advanced: [
      {
        id: 'mech_a_1',
        question: 'When performing laser alignment on coupled equipment, what is the maximum acceptable offset tolerance for equipment running at 3600 RPM?',
        options: ['0.010 inches', '0.002 inches or less', '0.050 inches', '0.125 inches'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_a_2',
        question: 'In resonance conditions, operating speed matches a natural frequency of the system and should be avoided.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_a_3',
        question: 'When analyzing vibration data, what frequency component typically indicates bearing defects?',
        options: ['1x running speed only', 'High-frequency random noise', 'Specific bearing fault frequencies (BPFI, BPFO, BSF, FTF)', 'Only sub-synchronous frequencies'],
        correct: 2,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_a_4',
        question: 'A vibration reading of 2x running speed typically indicates misalignment.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_a_5',
        question: 'What is the primary cause of cavitation in centrifugal pumps?',
        options: ['Excessive discharge pressure', 'Insufficient NPSH available', 'Too much lubrication', 'High fluid viscosity'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'mech_a_6',
        question: 'In predictive maintenance, infrared thermography can detect bearing problems before vibration analysis.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.MECHANICAL,
      },
      {
        id: 'mech_a_7',
        question: 'What does MTBF stand for in reliability engineering?',
        options: ['Maximum Time Before Failure', 'Mean Time Between Failures', 'Minimum Testing Before Function', 'Maintenance Time By Frequency'],
        correct: 1,
        domain: DOMAINS.MECHANICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ]
  },
  electrical: {
    entry: [
      {
        id: 'elec_e_1',
        question: 'What does the acronym LOTO stand for in electrical safety?',
        options: ['Lock Out, Tag Out', 'Load Operation, Test Output', 'Line Open, Terminal Off', 'Low Output, Total Ohms'],
        correct: 0,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_e_2',
        question: 'You should always assume electrical circuits are energized until verified otherwise.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_e_3',
        question: 'What instrument is used to measure electrical resistance?',
        options: ['Ammeter', 'Voltmeter', 'Ohmmeter', 'Wattmeter'],
        correct: 2,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_e_4',
        question: 'A fuse and a circuit breaker perform the same basic protective function.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_e_5',
        question: 'What color wire typically indicates ground in US electrical systems?',
        options: ['Black', 'White', 'Green or bare copper', 'Red'],
        correct: 2,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_e_6',
        question: 'AC stands for Alternating Current.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_e_7',
        question: 'What is the standard voltage for industrial three-phase power in the US?',
        options: ['120V', '240V', '480V', '600V'],
        correct: 2,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_e_8',
        question: 'A short circuit occurs when current bypasses its intended path.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_e_9',
        question: 'According to Ohm\'s Law, if voltage increases and resistance stays the same, current will:',
        options: ['Decrease', 'Stay the same', 'Increase', 'Become zero'],
        correct: 2,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ],
    intermediate: [
      {
        id: 'elec_i_1',
        question: 'In a three-phase motor, what is the most common cause of single-phasing?',
        options: ['Excessive lubrication', 'A blown fuse or open contactor contact in one phase', 'Too much load on the motor', 'Incorrect voltage rating'],
        correct: 1,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_i_2',
        question: 'Megger testing should be performed on energized circuits to get accurate insulation readings.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_i_3',
        question: 'What is the purpose of a motor starter overload relay?',
        options: ['To increase motor speed', 'To protect the motor from damage due to overcurrent conditions', 'To reduce starting current', 'To improve power factor'],
        correct: 1,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_i_4',
        question: 'When troubleshooting a motor that won\'t start, you should check the control circuit voltage first.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_i_5',
        question: 'What does a capacitor do in a single-phase motor circuit?',
        options: ['Provides starting torque by creating phase shift', 'Reduces voltage', 'Increases resistance', 'Stores mechanical energy'],
        correct: 0,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_i_6',
        question: 'A VFD (Variable Frequency Drive) controls motor speed by varying frequency and voltage.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_i_7',
        question: 'What is the relationship between motor poles and synchronous speed at 60Hz?',
        options: ['More poles = higher speed', 'More poles = lower speed', 'Poles don\'t affect speed', 'Only affects torque'],
        correct: 1,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_i_8',
        question: 'A 4-pole motor running on 60Hz has a synchronous speed of 1800 RPM.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_i_9',
        question: 'What is the purpose of a snubber circuit across a contactor coil?',
        options: ['Increase coil current', 'Suppress voltage spikes when coil de-energizes', 'Reduce contact bounce', 'Improve power factor'],
        correct: 1,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_i_10',
        question: 'Motor slip is the difference between synchronous speed and actual rotor speed.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      }
    ],
    advanced: [
      {
        id: 'elec_a_1',
        question: 'What is the acceptable insulation resistance reading for a 480V motor winding?',
        options: ['Less than 1 megohm', 'At least 1 megohm plus 1 megohm per 1000 volts', 'Exactly 480 ohms', '100 ohms minimum'],
        correct: 1,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_a_2',
        question: 'In VFD applications, reflected wave phenomenon can cause voltage spikes up to 2-3 times the DC bus voltage.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_a_3',
        question: 'When performing power quality analysis, what harmonic is most commonly associated with three-phase VFDs?',
        options: ['2nd harmonic', '3rd harmonic', '5th and 7th harmonics', '11th harmonic only'],
        correct: 2,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_a_4',
        question: 'A CT (Current Transformer) secondary should never be left open while the primary is energized.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_a_5',
        question: 'What is the purpose of a line reactor on a VFD input?',
        options: ['Increase motor speed', 'Reduce harmonic distortion and protect from voltage spikes', 'Improve motor cooling', 'Reduce motor torque'],
        correct: 1,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_a_6',
        question: 'Ground fault protection and short circuit protection are the same thing.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.ELECTRICAL,
      },
      {
        id: 'elec_a_7',
        question: 'In a wye-connected three-phase system, what is the relationship between line voltage and phase voltage?',
        options: ['Line voltage = Phase voltage', 'Line voltage = Phase voltage × √3', 'Line voltage = Phase voltage × 2', 'Line voltage = Phase voltage / 2'],
        correct: 1,
        domain: DOMAINS.ELECTRICAL,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'elec_a_8',
        question: 'Power factor correction capacitors should be installed on the load side of VFDs.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.ELECTRICAL,
      }
    ]
  },
  hydraulics: {
    entry: [
      {
        id: 'hydr_e_1',
        question: 'What is the primary purpose of hydraulic fluid in a hydraulic system?',
        options: ['To cool the system only', 'To transmit power, lubricate, and seal', 'To add weight to components', 'To prevent electrical conductivity'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_e_2',
        question: 'It is safe to check for hydraulic leaks using your hand.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_e_3',
        question: 'What component converts hydraulic pressure into linear mechanical force?',
        options: ['Pump', 'Cylinder', 'Filter', 'Reservoir'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_e_4',
        question: 'A hydraulic pump creates pressure.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_e_5',
        question: 'What is the purpose of a hydraulic reservoir?',
        options: ['Generate pressure', 'Store fluid, dissipate heat, and allow contaminants to settle', 'Control flow direction', 'Regulate system pressure'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_e_6',
        question: 'Air in a hydraulic system can cause spongy or erratic operation.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_e_7',
        question: 'What does a relief valve do in a hydraulic system?',
        options: ['Increases system pressure', 'Limits maximum system pressure', 'Filters contamination', 'Controls flow direction'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_e_8',
        question: 'Pneumatic systems use compressed air while hydraulic systems use fluid.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      }
    ],
    intermediate: [
      {
        id: 'hydr_i_1',
        question: 'What is the function of an accumulator in a hydraulic system?',
        options: ['Store hydraulic energy and smooth pressure fluctuations', 'Filter contamination', 'Heat the fluid', 'Measure flow rate'],
        correct: 0,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_i_2',
        question: 'Cavitation in a hydraulic pump is caused by insufficient fluid supply to the pump inlet.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_i_3',
        question: 'What type of hydraulic pump provides constant flow regardless of pressure?',
        options: ['Variable displacement pump', 'Fixed displacement pump', 'Pressure-compensated pump', 'Load-sensing pump'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_i_4',
        question: 'A flow control valve regulates the speed of hydraulic actuators.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_i_5',
        question: 'What is the purpose of a counterbalance valve?',
        options: ['Increase cylinder speed', 'Prevent uncontrolled movement of a load due to gravity', 'Filter hydraulic fluid', 'Regulate pump output'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_i_6',
        question: 'Hydraulic fluid viscosity that is too low can cause internal pump leakage.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_i_7',
        question: 'A directional control valve with designation 4/3 has:',
        options: ['4 ports and 3 positions', '4 positions and 3 ports', '4 liters capacity and 3 bar rating', '4 connections and 3 filters'],
        correct: 0,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_i_8',
        question: 'The ISO cleanliness code measures the particle contamination level in hydraulic fluid.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      }
    ],
    advanced: [
      {
        id: 'hydr_a_1',
        question: 'In proportional valve systems, dither frequency is used to overcome static friction and improve response.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_a_2',
        question: 'What is the beta ratio of a hydraulic filter?',
        options: ['Flow rate divided by pressure', 'Ratio of upstream to downstream particles of a given size', 'Filter element surface area', 'Pressure drop across filter'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_a_3',
        question: 'A servo valve provides more precise control than a proportional valve.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_a_4',
        question: 'What causes hydraulic system aeration?',
        options: ['Low fluid temperature', 'Air entering through pump inlet leaks or low reservoir levels', 'High system pressure', 'Clean hydraulic fluid'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'hydr_a_5',
        question: 'Intensifiers in hydraulic systems can achieve pressures higher than the main system pressure.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_a_6',
        question: 'A pressure-compensated pump reduces its displacement when system pressure reaches a set value.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.HYDRAULICS,
      },
      {
        id: 'hydr_a_7',
        question: 'What is the purpose of a pilot-operated check valve?',
        options: ['Filter contamination', 'Allow reverse flow when pilot pressure is applied', 'Regulate pump speed', 'Measure flow rate'],
        correct: 1,
        domain: DOMAINS.HYDRAULICS,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ]
  },
  plc: {
    entry: [
      {
        id: 'plc_e_1',
        question: 'What does PLC stand for?',
        options: ['Power Line Controller', 'Programmable Logic Controller', 'Pneumatic Lift Control', 'Pressure Level Coordinator'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_e_2',
        question: 'A PLC scans its program continuously in a repeating cycle.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_e_3',
        question: 'What type of input would a pushbutton typically be connected to?',
        options: ['Analog input', 'Digital/discrete input', 'High-speed counter', 'Thermocouple input'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_e_4',
        question: 'A normally open (NO) contact in a PLC ladder diagram passes power when the associated input is ON.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_e_5',
        question: 'What does a normally closed (NC) contact do when its associated input is energized?',
        options: ['Passes power', 'Blocks power', 'Alternates states', 'Creates a short circuit'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_e_6',
        question: 'An analog input can read values like temperature and pressure.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_e_7',
        question: 'What is the function of an output module in a PLC?',
        options: ['Read sensor data', 'Execute program logic', 'Control external devices like motors and solenoids', 'Store program memory'],
        correct: 2,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_e_8',
        question: 'A 4-20mA signal is a common analog signal standard in industrial applications.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      }
    ],
    intermediate: [
      {
        id: 'plc_i_1',
        question: 'What is the purpose of a watchdog timer in a PLC?',
        options: ['To time production cycles', 'To detect processor faults and restart the system if scan time exceeds limits', 'To count products', 'To delay motor starts'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_i_2',
        question: 'In ladder logic, an OTE instruction represents an output coil.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_i_3',
        question: 'What is the difference between a retentive and non-retentive timer?',
        options: ['Retentive timers are faster', 'Retentive timers maintain accumulated time when disabled', 'Non-retentive timers have longer ranges', 'There is no difference'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_i_4',
        question: 'A TON timer output is true when the accumulated value equals or exceeds the preset value.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_i_5',
        question: 'What instruction would you use to increment a value each time a sensor is triggered?',
        options: ['Timer (TON)', 'Counter (CTU)', 'Move (MOV)', 'Compare (CMP)'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_i_6',
        question: 'A latch (OTL) instruction will remain energized even after its input condition goes false.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_i_7',
        question: 'What does HMI stand for?',
        options: ['High Motor Interface', 'Human Machine Interface', 'Hydraulic Monitoring Indicator', 'Heat Management Instrument'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_i_8',
        question: 'Forcing an I/O point in a PLC should only be done for troubleshooting and with proper precautions.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_i_9',
        question: 'What is the purpose of a one-shot instruction?',
        options: ['To create a pulse for one scan when triggered', 'To permanently latch an output', 'To count multiple events', 'To delay an output'],
        correct: 0,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ],
    advanced: [
      {
        id: 'plc_a_1',
        question: 'In industrial Ethernet networks, Quality of Service (QoS) can prioritize time-critical control data over general traffic.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_a_2',
        question: 'What communication protocol is commonly used for high-speed motion control?',
        options: ['Modbus RTU', 'EtherNet/IP with CIP Motion', 'HART', 'BACnet'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_a_3',
        question: 'A PID loop with excessive integral action can cause overshoot and oscillation.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_a_4',
        question: 'What does the "D" term in a PID controller respond to?',
        options: ['Current error value', 'Sum of past errors', 'Rate of change of error', 'Setpoint value'],
        correct: 2,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_a_5',
        question: 'An Add-On Instruction (AOI) allows you to create reusable code blocks.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_a_6',
        question: 'What is the purpose of a User-Defined Data Type (UDT)?',
        options: ['Increase scan time', 'Create custom structured data for organized programming', 'Reduce memory usage', 'Disable safety features'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'plc_a_7',
        question: 'Deterministic communication means data arrives within a guaranteed time window.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.PLC,
      },
      {
        id: 'plc_a_8',
        question: 'What is the function of a safety PLC compared to a standard PLC?',
        options: ['Faster processing speed', 'Designed for safety-critical applications with redundant processing and diagnostics', 'Lower cost', 'Larger memory capacity'],
        correct: 1,
        domain: DOMAINS.PLC,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ]
  },
  safety: {
    entry: [
      {
        id: 'safe_e_1',
        question: 'What is the primary purpose of a Job Safety Analysis (JSA)?',
        options: ['To slow down work', 'To identify hazards and determine safe work procedures', 'To create paperwork', 'To assign blame for accidents'],
        correct: 1,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_e_2',
        question: 'Stored energy (capacitors, springs, pressurized lines) must be released before working on equipment.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_e_3',
        question: 'What does PPE stand for?',
        options: ['Personal Protection Equipment', 'Personal Protective Equipment', 'Preventive Protection Elements', 'Primary Protection Essentials'],
        correct: 1,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_e_4',
        question: 'It is acceptable to remove machine guards temporarily to speed up production.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_e_5',
        question: 'What should you do first if you discover a hazardous condition?',
        options: ['Ignore it', 'Fix it yourself immediately', 'Report it and secure the area', 'Wait for someone else to notice'],
        correct: 2,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_e_6',
        question: 'Only qualified personnel should perform electrical work.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_e_7',
        question: 'What is the purpose of an SDS (Safety Data Sheet)?',
        options: ['To track inventory', 'To provide hazard and handling information for chemicals', 'To schedule maintenance', 'To record production data'],
        correct: 1,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_e_8',
        question: 'Lockout/Tagout procedures are only required for electrical hazards.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.SAFETY,
      }
    ],
    intermediate: [
      {
        id: 'safe_i_1',
        question: 'A confined space entry permit is only required if the space contains a known hazard.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_i_2',
        question: 'What is the minimum safe approach distance for unqualified workers near exposed 480V conductors?',
        options: ['1 foot', '3.5 feet', '10 feet', '25 feet'],
        correct: 2,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_i_3',
        question: 'Arc flash hazard increases with higher fault current and longer clearing time.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_i_4',
        question: 'What PPE category requires an arc-rated face shield and balaclava?',
        options: ['Category 1', 'Category 2', 'Category 3 or higher', 'No category requires this'],
        correct: 2,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_i_5',
        question: 'Hot work permits are required only for welding operations.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_i_6',
        question: 'What is the purpose of a safety interlock on a machine guard?',
        options: ['To increase production speed', 'To stop the machine when the guard is opened', 'To improve machine accuracy', 'To reduce energy consumption'],
        correct: 1,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_i_7',
        question: 'Energy isolation must be verified before starting work on equipment.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_i_8',
        question: 'What oxygen level defines an oxygen-deficient atmosphere?',
        options: ['Below 23.5%', 'Below 19.5%', 'Below 15%', 'Below 10%'],
        correct: 1,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ],
    advanced: [
      {
        id: 'safe_a_1',
        question: 'NFPA 70E requires electrical safety training for qualified workers to be conducted at least every three years.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_a_2',
        question: 'What is the hierarchy of controls for hazard mitigation (most to least effective)?',
        options: ['PPE, Engineering, Elimination', 'Elimination, Substitution, Engineering, Administrative, PPE', 'Administrative, Engineering, PPE', 'Substitution, PPE, Elimination'],
        correct: 1,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_a_3',
        question: 'A risk assessment considers both the severity and probability of a hazard.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_a_4',
        question: 'What does SIL stand for in functional safety?',
        options: ['System Integration Level', 'Safety Integrity Level', 'Safe Installation Limit', 'Standard Industrial Logic'],
        correct: 1,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_a_5',
        question: 'Machine safety standards ISO 13849 and IEC 62061 address the same functional safety requirements using different methodologies.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.SAFETY,
      },
      {
        id: 'safe_a_6',
        question: 'What is the purpose of a safety relay with redundant contacts?',
        options: ['Increase switching speed', 'Provide fault detection through monitoring', 'Reduce installation cost', 'Simplify wiring'],
        correct: 1,
        domain: DOMAINS.SAFETY,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'safe_a_7',
        question: 'Category B in ISO 13849 provides the lowest level of risk reduction.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.SAFETY,
      }
    ]
  },
  troubleshooting: {
    entry: [
      {
        id: 'trou_e_1',
        question: 'What is the first step in systematic troubleshooting?',
        options: ['Replace all suspected components', 'Gather information and understand normal operation', 'Call a supervisor', 'Start replacing parts randomly'],
        correct: 1,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_e_2',
        question: 'Documentation of repairs and findings is an important part of the troubleshooting process.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_e_3',
        question: 'What does "divide and conquer" mean in troubleshooting?',
        options: ['Split the work among team members', 'Systematically isolate the problem by testing sections of a system', 'Replace half the components', 'Work on multiple machines simultaneously'],
        correct: 1,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_e_4',
        question: 'When troubleshooting, you should change multiple variables at once to save time.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_e_5',
        question: 'What is the value of checking the simplest possible causes first?',
        options: ['It wastes time', 'Simple problems are most common and easiest to fix', 'It shows inexperience', 'Complex problems should be addressed first'],
        correct: 1,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_e_6',
        question: 'Operator input is not valuable for troubleshooting since they are not technicians.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_e_7',
        question: 'What should you do after successfully repairing equipment?',
        options: ['Move to the next job immediately', 'Verify proper operation and document the repair', 'Let the operator test it alone', 'Remove all safety guards'],
        correct: 1,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ],
    intermediate: [
      {
        id: 'trou_i_1',
        question: 'A motor draws high current but won\'t start. What is the most likely cause?',
        options: ['Locked rotor or mechanical bind', 'Perfect operating condition', 'Low voltage supply', 'Motor is too cold'],
        correct: 0,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_i_2',
        question: 'Intermittent faults are often more difficult to diagnose than permanent faults.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_i_3',
        question: 'A hydraulic cylinder moves slowly in one direction but normally in the other. What is the most likely cause?',
        options: ['Low fluid level', 'Worn piston seals causing internal bypass', 'Clogged tank breather', 'Wrong fluid type'],
        correct: 1,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_i_4',
        question: 'If a PLC input LED is on but the program doesn\'t see the input, the problem is likely in the input module or wiring.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_i_5',
        question: 'What does a burnt smell from an electric motor usually indicate?',
        options: ['Normal operation', 'Need for lubrication', 'Insulation damage from overheating', 'Bearing wear'],
        correct: 2,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_i_6',
        question: 'Root cause analysis should stop once the immediate cause is found.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_i_7',
        question: 'A VFD displays an overcurrent fault at startup. What should you check first?',
        options: ['VFD parameter settings', 'Motor and load for mechanical binding', 'Power supply voltage', 'All of the above'],
        correct: 3,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_i_8',
        question: 'Comparing readings to a known good machine can help identify abnormal conditions.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.TROUBLESHOOTING,
      }
    ],
    advanced: [
      {
        id: 'trou_a_1',
        question: 'Predictive maintenance techniques can identify problems before functional failure occurs.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_a_2',
        question: 'What vibration signature typically indicates a bent shaft?',
        options: ['High 1x axial vibration', 'Random high-frequency noise', 'Only 2x radial vibration', 'No vibration change'],
        correct: 0,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_a_3',
        question: 'Oil analysis can detect wear particles, contamination, and fluid degradation.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_a_4',
        question: 'What does a "bathtub curve" represent in reliability engineering?',
        options: ['Optimal fluid levels', 'Failure rate over equipment lifecycle', 'Temperature distribution', 'Pressure differential'],
        correct: 1,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_a_5',
        question: 'Infrared thermography requires equipment to be shut down for accurate readings.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: false,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_a_6',
        question: 'What is the "5 Why" technique used for?',
        options: ['Training new employees', 'Finding root cause by asking why repeatedly', 'Scheduling maintenance', 'Ordering spare parts'],
        correct: 1,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      },
      {
        id: 'trou_a_7',
        question: 'Ultrasonic testing can detect leaks, electrical arcing, and bearing defects.',
        type: QUESTION_TYPES.TRUE_FALSE,
        correct: true,
        domain: DOMAINS.TROUBLESHOOTING,
      },
      {
        id: 'trou_a_8',
        question: 'What trending method compares current readings to baseline measurements?',
        options: ['Absolute trending', 'Comparative trending', 'Statistical trending', 'All of the above are valid methods'],
        correct: 3,
        domain: DOMAINS.TROUBLESHOOTING,
        type: QUESTION_TYPES.MULTIPLE_CHOICE,
      }
    ]
  }
};

export const STORAGE_KEYS = {
  SAVED_ASSESSMENTS: 'savedAssessments',
  COMPLETED_ASSESSMENTS: 'completedAssessments',
};

export const ADMIN_CONFIG = {
  DEFAULT_PASSWORD: 'Blistex1800!!',
  SESSION_TIMEOUT: 3600000,
};